### ISSUE TITLE
Sending users without email addresses

### ISSUE THREAD

**Issue by wcjohnson11** [segment-integrations/integration-customer.io#2]
The integration is sending users into Customer.io from .identify() calls even if the user has no email address as a property on the call. This is a problem because Customer.io bills by number of users you have in your Customer.io interface and people using this integration shouldn't be paying for people they can't contact.

**Comment by sperand-io** [comment]
I think this is still expected behavior though, as c.io _does_ allow you to send users without userId. I think the line here is they should selectively omit customer.io from downstream providers a la:

```
analytics.identify('uid', {/* traits */}, { integrations: { "Customer.io": false }});
```
