### ISSUE TITLE
CreatedAt creates duplicate properties

### ISSUE THREAD

**Issue by guillaumecabane** [segment-integrations/integration-customer.io#3]
When passing the standard property "CreatedAt" to segment it will creates duplicate properties in customer.io : Created_at AND CreatedAt

![image](https://cloud.githubusercontent.com/assets/1849807/6510598/6090a7c4-c367-11e4-871c-f98e603d3111.png)
![image](https://cloud.githubusercontent.com/assets/1849807/6510600/6347e45a-c367-11e4-88a1-787e750fec1f.png)

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue! https://github.com/segment-integrations/integration-customerio/blob/master/test/fixtures/identify-basic.json#L14 Does not seem to be an issue anymore
