### ISSUE TITLE
Don't send _last_visit in identify() calls

### ISSUE THREAD

**Issue by philfreo** [segment-integrations/integration-customer.io#6]
Customer.io apparently has an undocumented field called `_last_visit` which it looks like you're sending in `analytics.identify(...)` calls.

When sending this field it looks like it's updating the "Last Visited" field of a Customer.io People profile.

Sending `_last_visit` perhaps makes sense in some methods (e.g. logging a page view) but to me does _not_ belong in `identify()` calls.

The reason is that I thought you should be able to use `identify` to batch send updates from the server to Customer.io about the customer's account even if they haven't visited. (For example: call `identify` with a trait about whether a user's trial is expired, or if their credit card is declining, regardless of when they last logged in).

It turns out that when using [customerio-python's identify()](https://github.com/customerio/customerio-python#create-or-update-a-customerio-customer-profile) directly, that "Last Visited" is _not_ updated. I would expect Segment to do the same.

See also:
- https://twitter.com/customerio/status/524965460278652928
- https://github.com/segmentio/integrations/issues/12

Let me know what you think.

/cc @alisdair @customerio @calvinfo @screaser

**Comment by screaser** [comment]
Your analysis seems correct to me!
